urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from apps.core.views import IndexView
from apps.tweets.views import UploadExportView, CurrentView, KeepView, DeleteView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls", namespace="social")),
    path("", IndexView.as_view(), name="index"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("upload_export/", UploadExportView.as_view(), name="upload_export"),
    path("current/", CurrentView.as_view(), name="current"),
    path("keep/", KeepView.as_view(), name="keep"),
    path("delete/", DeleteView.as_view(), name="delete"),
]

apps/tweets/models.py
from django.db import models


class TotalTweets(models.Model):

    user = models.OneToOneField("auth.User", on_delete=models.CASCADE, related_name="total_tweets")
    total = models.PositiveIntegerField()


class Tweet(models.Model):

    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    tweet_id = models.BigIntegerField()
    tweeted = models.DateTimeField()

apps/tweets/forms.py
from django import forms
from django.core.validators import FileExtensionValidator


class UploadExportForm(forms.Form):

    export = forms.FileField(label="Export file", validators=[FileExtensionValidator(allowed_extensions=["js"])])

apps/core/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):

    template_name = "index.html"

apps/tweets/views.py
import json
from io import StringIO

import twitter
from dateutil.parser import parse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import default_storage
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.shortcuts import redirect
from django.views import View
from django.views.generic import FormView
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from sentry_sdk import capture_exception

from apps.tweets.forms import UploadExportForm
from apps.tweets.models import Tweet, TotalTweets


class UploadExportView(LoginRequiredMixin, FormView):

    form_class = UploadExportForm
    template_name = "upload_export.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user and request.user.is_authenticated:
            try:
                if request.user.total_tweets:
                    messages.error(request, _("You've already imported your tweets."))
                    return redirect("index")
            except ObjectDoesNotExist:
                pass
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        file = form.cleaned_data["export"]

        text = file.read().decode("utf-8")

        try:
            text = text.replace("window.YTD.tweet.part0 = ", "")
            data = json.loads(text)
        except ValueError:
            filename = default_storage.save(f"import_{timezone.now().isoformat()}.js", StringIO(text))  # noqa:
            capture_exception()
            messages.error(self.request, _("Invalid format of the export file."))
            return redirect("upload_export")

        tweets = []

        for tweet in data:
            tweets.append(Tweet(user=self.request.user, tweet_id=tweet["id"], tweeted=parse(tweet["created_at"])))

        Tweet.objects.bulk_create(tweets, batch_size=100)

        TotalTweets.objects.create(user=self.request.user, total=len(tweets))

        messages.success(self.request, _("Tweets were uploaded, you can start the review."))

        return redirect("index")


def get_api(user):
    auth_data = user.social_auth.get()
    api = twitter.Api(
        consumer_key=settings.SOCIAL_AUTH_TWITTER_KEY,
        consumer_secret=settings.SOCIAL_AUTH_TWITTER_SECRET,
        access_token_key=auth_data.extra_data["access_token"]["oauth_token"],
        access_token_secret=auth_data.extra_data["access_token"]["oauth_token_secret"],
    )

    return api


class CurrentView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            total_tweets = request.user.total_tweets
        except ObjectDoesNotExist:
            return HttpResponseBadRequest()

        api = get_api(request.user)

        while True:
            try:
                tweet = Tweet.objects.filter(user=request.user).earliest("tweeted")
            except ObjectDoesNotExist:
                return JsonResponse(
                    {"tweet": None, "total": total_tweets.total, "processed": total_tweets.total, "progress": 100}
                )
            else:
                try:
                    api.GetStatus(tweet.tweet_id)
                    break
                except twitter.error.TwitterError as e:  # doesn't exist anymore
                    message = e.message[0]

                    if message["code"] == 89:
                        return JsonResponse({"expired": True})
                    elif message["code"] in {144, 179}:
                        tweet.delete()
                    else:
                        capture_exception()
                        return JsonResponse({"error": message}, status=500)

        total = total_tweets.total
        processed = total_tweets.total - Tweet.objects.filter(user=request.user).count()
        progress = round(processed / total * 100, 2)

        return JsonResponse(
            {"tweet": str(tweet.tweet_id), "total": total_tweets.total, "processed": processed, "progress": progress}
        )


class KeepView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            tweet = Tweet.objects.get(user=request.user, tweet_id=request.GET["tweet_id"])
        except (KeyError, ObjectDoesNotExist):
            return HttpResponseBadRequest()

        tweet.delete()

        return HttpResponse()


class DeleteView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            tweet = Tweet.objects.get(user=request.user, tweet_id=request.GET["tweet_id"])
        except (KeyError, ObjectDoesNotExist):
            return HttpResponseBadRequest()

        api = get_api(request.user)

        api.DestroyStatus(tweet.tweet_id)

        tweet.delete()

        return HttpResponse()

apps/core/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}OTteR - Old Tweets Reviewer{% endblock %}</title>

    <style>
        .container {
            width: auto;
            max-width: 680px;
            padding: 0 15px;
            margin-top: 5%;
        }

        @media (max-width: 680px) {
            .container {
                margin-top: 1%;
            }
        }

        #progress {
            position: fixed;
            top: 0;
            left: 0;
            width: 0%;
            height: 5px;
            background-color: lightblue;
        }

        #progress_text {
            position: absolute;
            bottom: 10px;
            right: 20px;
            border-radius: 5px;
            border: 1px solid black;
            padding: 3px;
            background-color: white;
        }

        .twitter-tweet {
            margin: 0 auto;
        }

    </style>
</head>
<body>
{% if user.is_authenticated %}
    <div id="progress">

    </div>
{% endif %}

<main role="main" class="container">
    <h1>
        <span title="Old Tweets Reviewer">OTteR</span>
        <small style="font-size: 40%;">
            <a href="https://gitlab.com/mikulaspoul/otter" target="_blank">Source</a> | <a href="https://twitter.com/miki_cz" target="_blank">Author</a>
        </small>
    </h1>

    {% include "messages.html" %}
    {% block content %}

    {% endblock %}
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block javascript %}
{% endblock %}
</body>
</html>

apps/core/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% if not user.is_authenticated %}
        <p>
            This apps allows you to go through your tweets one by one and delete those you want.
            You just need to request your Twitter data and upload the list of tweets.
            Than the app shows you the tweets and allows you to delete some tweets, while remembering where you were for when you return in the future.
            The app stores the minimum amount of data possible while using the Twitter API as least as possible.
        </p>
    {% endif %}

    <div class="text-center">
        {% if not user.is_authenticated %}
            <hr>

            <a class="btn btn-primary" href="{% url "social:begin" "twitter" %}">Log in using twitter</a>

            <div class="text-left">
            <p>
                This app will ask for permissions to access your Twitter and manage it.
                However it only actually uses the permission to delete tweets.
            </p>

            <p>List of stored information</p>

            <ul>
                <li>Username</li>
                <li>Full name</li>
                <li>User ID</li>
                <li>List of tweet IDs and their date (only after upload of export)</li>
                <li>Total number of tweets</li>
            </ul>
            </div>
        {% else %}
            Logged in as <a href="https://twitter.com/{{ user.username }}">{{ user }}</a>.
            <a href="{% url "logout" %}">Logout</a>
        {% endif %}

        {% if user.is_authenticated %}
            <hr>

            {% if not user.tweet_set.count %}
                <a href="{% url "upload_export" %}" class="btn btn-primary">Upload export of twitter data</a>
            {% else %}

                <div class="btn-group">
                    <button type="button" class="btn btn-success">KEEP</button>
                    <button type="button" class="btn btn-danger">DELETE</button>
                </div>

                <div id="tweet-container">

                </div>

                <div id="progress_text">
                    <span class="processed"></span> of <span class="total"></span>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

{% block javascript %}
<script sync src="https://platform.twitter.com/widgets.js"></script>
<script type="text/javascript">
    let progress_el = $("#progress");
    let current_tweet = null;
    load_current = function () {
       if (!progress_el) {
           return;
       }

       let processed_el = $("#progress_text .processed");
       let total_el = $("#progress_text .total");

       $.ajax({
           "method": "GET",
           "url": "/current/",
       }).done(function (data) {
           if (data.expired) {
               window.location = "/";
               return;
           }

           processed = data.processed;
           progress = data.progress;
           total = data.total;
           tweet = data.tweet;

           current_tweet = tweet;

           progress_el.css("width", progress + "%");
           total_el.text(total);
           processed_el.text(processed);

           twttr.widgets.createTweet(tweet, document.getElementById("tweet-container"), {
               "conversation": "all",
               "cards": "visible",
           });
       })
    };

    action = function (t) {
        if (!current_tweet) {
            return;
        }
        $.ajax({
            "method": "GET",
            "url": "/" + t + "/",
            "data": {
                "tweet_id": current_tweet
            }
        }).done(function (response) {
            $("#tweet-container").empty();
            load_current()
        })
    };

    $(document).ready(load_current);
    $(".btn-group .btn-success").on("click", function () {
        action("keep")
    });
    $(".btn-group .btn-danger").on("click", function () {
        action("delete")
    });

</script>
{% endblock %}

apps/core/templates/messages.html
{% for message in messages %}
    <div class="alert alert-{% if message.tags == "error" %}danger{%else%}{{message.tags}}{%endif%}">
        {{ message }}
    </div>
{% endfor %}

apps/tweets/templates/upload_export.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <p>
        Here you can upload the export of your tweets for them to be reviewed.
        This is necessary because you can only access the last 3200 tweets using the twitter API.
        The manual for requesting your Twitter data is <a href="https://help.twitter.com/en/managing-your-account/accessing-your-twitter-data" target="_blank">here</a>.
        You need to download it and upload the file <code>tweet.js</code>.
    </p>

    <form action="." method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <div class="text-center">
            <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
        </div>
    </form>
{% endblock %}